---
vlans:

  - name: DATA
    site: sana
    status: reserved
    tenant: Consulting
    vid: 10
    vlan_group: HM_VLANS
    vlan_role: Branch_Data

  - name: VOICE
    site: sana
    status: reserved
    tenant: Consulting
    vid: 20
    vlan_group: HM_VLANS
    vlan_role: Branch_Voice

  - name: B_WIFI
    site: sana
    status: reserved
    tenant: Consulting
    vid: 30
    vlan_group: HM_VLANS
    vlan_role: Branch_WiFi

  - name: G_WIFI
    site: sana
    status: reserved
    tenant: Consulting
    vid: 40
    vlan_group: HM_VLANS
    vlan_role: Guest_WiFi

  - name: NETMAN
    site: sana
    status: reserved
    tenant: Consulting
    vid: 50
    vlan_group: HM_VLANS
    vlan_role: Network_Management
    
  - name: P2P
    site: sana
    status: reserved
    tenant: Consulting
    vid: 60
    vlan_group: HM_VLANS
    vlan_role: Point_to_Point


  - name: LMTB
    site: sana
    status: reserved
    tenant: Consulting
    vid: 70
    vlan_group: HM_VLANS
    vlan_role: Radio-Access-Nework-SiteLan
